const ELLIA_FILE_URI_RE = /^ellia:\/\/file\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i

export interface ElliaFileReference {
  fileId: string
}

/**
 * Parse the canonical editor-owned file URI.
 *
 * File ids are UUIDs generated by the server. Keep the original casing in the
 * returned value so a source string can be represented without normalization.
 */
export function parseElliaFileReference(value: string): ElliaFileReference | null {
  const match = ELLIA_FILE_URI_RE.exec(value)
  if (!match) return null
  const fileId = match[1]
  if (!fileId) return null
  return { fileId }
}

export function buildElliaFileUri(fileId: string): string {
  return `ellia://file/${fileId}`
}

/**
 * Build the same-origin URL used by the authenticated file endpoint.
 *
 * `origin` is injectable for deterministic tests and defaults to the browser's
 * current origin. The returned path always starts at `/api`, which also keeps
 * working with the Vite development proxy.
 */
export function buildFileAccessUrl(fileId: string, origin = currentOrigin()): string {
  return new URL(`/api/files/${encodeURIComponent(fileId)}`, origin).toString()
}

export function buildMarkdownImageReference(fileName: string | null | undefined, fileId: string): string {
  const alt = escapeMarkdownImageAlt(fileName?.trim() || fileId)
  return `![${alt}](${buildElliaFileUri(fileId)})`
}

function currentOrigin(): string {
  return typeof window === 'undefined' ? 'http://localhost' : window.location.origin
}

function escapeMarkdownImageAlt(value: string): string {
  return value
    .replace(/[\\`*_\[\]~]/g, '\\$&')
    .replace(/\r?\n/g, ' ')
}
