import type { StoryNode } from '@/composables/useStoryDialog'
import keiAmasImg from '/images/kei_full_body/kei_amas立绘.png?url'
import rioWinterImg from '/images/rio/rio_冬装.png?url'

const keiBirthStage = [
  { id: 'kei', image: keiAmasImg, position: 'left' as const, speakerNames: ['柯伊'], animation: 'fade' as const, anchorY: 0.66 },
  { id: 'rio', image: rioWinterImg, position: 'right' as const, speakerNames: ['莉音'], animation: 'fade' as const, anchorY: 0.4 },
]

export const keiBirthScript: StoryNode[] = [
  { speaker: '莉音', text: '总之现在的重点是决定接下来该做什么。', stageCharacters: keiBirthStage },
  { speaker: '莉音', text: '所以我决定先来制造Kei的身体。' },
  { speaker: '柯伊', text: '咦？' },
  { speaker: '爱丽丝', text: '嗯？' },
  { speaker: '柯伊', text: '不是，等等。先等一下！' },
  { speaker: '柯伊', text: '事情为什么会变成那样！？' },
  { speaker: '莉音', text: 'Kei现在的状况，就和脖子以下全数坏斯的植物人没两样。' },
  { speaker: '莉音', text: '所以才会导致他累积了更多不满吧。' },
  { speaker: '日鞠', text: '原来如此，就是那股不满加剧了Kei的暴力性，导致无法进行对话……' },
  { speaker: '日鞠', text: '你的分析还算合理呢，莉音。' },
  { speaker: '老师', text: '“哦，听你这么一说，好像确实如此。”' },
  { speaker: '莉音', text: '谢谢你们这么快就能理解我的意思，日鞠、老师。' },
  { speaker: '柯伊', text: '不是，先等一下。' },
  { speaker: '柯伊', text: '别把我丢在一旁自说自话好吗？' },
  { speaker: '柯伊', text: '除此之外，光是莉音加入这个话题这件事本身，就让我莫名觉得非常不安耶……？' },
  { speaker: '日鞠', text: '那么该由谁来制造Kei的身体呢？' },
  { speaker: '莉音', text: '由我来吧。我正好带了很多AMAS过来，备用零件和机体应该也够用。' },
  { speaker: '柯伊', text: '你们有在听我说话吗？' },
  { speaker: '柯伊', text: '我刚才明明说了光是莉音在谈论这个话题，就会让我产生难以忍受的危机感啊！？' },
  { speaker: '艾米', text: '你打算怎么使用AMAS呢，会长？' },
  { speaker: '艾米', text: '这种时候我通常都是接受指示的一方。' },
  { speaker: '时', text: '请不必担心。莉音大人的品味一向都是独一无二的。' },
  { speaker: '柯伊', text: '不是，就说了先等等！？' },
  { speaker: '柯伊', text: '独一无二并不总是正面的形容吧！？' },
  { speaker: '柯伊', text: '这种程度的事情，大家应该都有能力判断吧！？' },
  { speaker: '柯伊', text: '咿……！' },
  { speaker: '爱丽丝', text: '……真的要制造Kei的身体吗，莉音前辈？' },
  { speaker: '爱丽丝', text: '爱丽丝，爱丽丝……能再次触摸到Kei吗……？' },
  { speaker: '柯伊', text: '王，王女！？！？' },
  { speaker: '莉音', text: '没错。虽然我不清楚这么说话适不适合……' },
  { speaker: '莉音', text: '尽管相信我吧，爱丽丝。' },
  { speaker: '爱丽丝', text: '谢谢你，莉音前辈！还有日鞠前辈也是！' },
  { speaker: '日鞠', text: '嗯，爱丽丝。我们会全力以赴的。' },
  { speaker: '柯伊', text: '拜托你们听别人说话！我正在求救啊！' },
  { speaker: '老师', text: '“你先冷静，Kei。大家都在想办法帮助Kei哦。”' },
  { speaker: '柯伊', text: '尊重一下受助者的意愿行吗！？' },
  { speaker: '柯伊', text: '拜托先阻止那个一边追求合理性、一边坚持自我美感的人好不好！？' },
  { speaker: '老师', text: '“冷静点，Kei。工程已经开始了。”' },
  { speaker: '柯伊', text: '呃啊啊啊啊啊！' },
  { speaker: '莉音', text: '真前卫啊……' },
  { speaker: '柯伊', text: '……。' },
  { speaker: '老师', text: '“那个……Kei？你也发表一下感想吧……？”' },
  { speaker: '柯伊', text: '我要回资料里了。' },
  { speaker: '艾米', text: '不行哦，Kei。' },
  { speaker: '艾米', text: '大家都这么努力了。' },
  { speaker: '艾米', text: '尤其我特别喜欢这个轮子的结构。' },
  { speaker: '艾米', text: '因为靠双脚行走其实不是很有效率。' },
  { speaker: '艾米', text: '而且还有能在发生意外时保证飞行能力的推进器……' },
  { speaker: '艾米', text: '真不愧是莉音会长，简直是合理性的极致啊。' },
  { speaker: '时', text: '没错，Kei。以前有句话叫“逃走只能得到一个，前进就能得到两个”。' },
  { speaker: '时', text: '所以现在不是逃避的时候。' },
  { speaker: '柯伊', text: '你真的知道那句话是什么意思吗！？' },
  { speaker: '时', text: '老实说我其实不知道。' },
  { speaker: '柯伊', text: '呃啊啊啊——！' },
  { speaker: '柯伊', text: '日鞠、莉音！你们也说点什么啊！到底是怎样啊！' },
  { speaker: '日鞠', text: '……我还是少说几句吧。' },
  { speaker: '日鞠', text: '刚好我也想起一件非常重要且不能拖延的事，所以先告辞了。' },
  { speaker: '柯伊', text: '你想逃跑吗！' },
  { speaker: '莉音', text: '真前卫啊……' },
  { speaker: '柯伊', text: '你只剩下这句台词了是不是！' },
  { speaker: '老师', text: '“……Kei你先冷静。无论如何，现在你已经有能够行动的身体了。”' },
  { speaker: '老师', text: '“哇，真是可喜可贺……要不要来握个手？”' },
  { speaker: '柯伊', text: '这全都是老师的错！' },
  { speaker: '老师', text: '“为什么？！”' },
  { speaker: '艾米', text: '总之，现在差不多该开始准备了吧？' },
  { speaker: '柯伊', text: '要准备什么……？' },
  { speaker: '柯伊', text: '莫名有股不祥的预感……' },
  { speaker: '艾米', text: '当然是准备见正在等Kei的王女咯。' },
  { speaker: '柯伊', text: '……！' },
  { speaker: '柯伊', text: '我真的不能回资料里去吗……？？？' },
  { speaker: '时', text: '不可以，Kei。' },
  { speaker: '时', text: '如果你那么做的话，可爱的爱丽丝一定会很难过的。' },
  { speaker: '柯伊', text: '为什么只有这种时候才会好好说话啊！！！' },
  { speaker: '老师', text: '“这个嘛……就是现在！”' },
]
